### ISSUE TITLE
Performance Guide

### ISSUE THREAD

**Issue by mattcary** [google/gvisor-website#101]
Hi,

In the performance guide page, the graphs aren't showing up for me. I just get raw text like

{{< graph id=“sysbench-memory” url=“/performance/sysbench-memory.csv” title=“perf.py sysbench.memory –runtime=runc –runtime=runsc” >}}

instead of the embedding graph which should presumably be displayed instead.

Thanks

Matt

**Comment by prattmic** [comment]
Duplicate of #99
