### ISSUE TITLE
Daily build is not available

### ISSUE THREAD

**Issue by shield-9** [google/gvisor-website#107]
https://gvisor.dev/docs/user_guide/docker/ said:
> Older builds can also be found here: https://storage.googleapis.com/gvisor/releases/nightly/${yyyy-mm-dd}/runsc

But it looks like that is currently not available.
e.g. https://storage.googleapis.com/gvisor/releases/nightly/2019-09-07/runsc

**Comment by ianlewis** [comment]
Some days don't get builds because their tests were failing or for some other reason. You can backtrack to a previous day or use https://storage.googleapis.com/gvisor/releases/nightly/latest/runsc

**Comment by ianlewis** [comment]
I'll try to add a note about that in the docs.

**Comment by shield-9** [comment]
Thank you!

**Comment by amscanne** [comment]
Note that I'm working on making the builds much more reliable, and also automatically publishing apt repositories for all tagged releases. The docs will updated with information about this soon.
