### ISSUE TITLE
Performance Guide - Grammar issue - 'This an implementation cost'

### ISSUE THREAD

**Issue by sinfere** [google/gvisor-website#147]
Second, as gVisor is an independent implementation of the system call surface, many of the subsystems or specific calls are not as optimized as more mature implementations. A good example here is the network stack, which is continuing to evolve but does not support all the advanced recovery mechanisms offered by other stacks and is less CPU efficient. ```This an implementation cost and is distinct from structural costs```. Improvements here are ongoing and driven by the workloads that matter to gVisor users and contributors.

```This an implementation cost``` should be ```This is an implementation cost```, right?

**Comment by ianlewis** [comment]
You're probably right. You can click on the edit link on that page to submit a PR to fix it.
