### ISSUE TITLE
Not showing up in search engines

### ISSUE THREAD

**Issue by ianlewis** [google/gvisor-website#39]
gvisor.dev isn't showing up in search engines. Need to investigate what's wrong.

**Comment by prattmic** [comment]
At the top of the HTML, I see:

```
<META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">
```

That sounds rather suspicious to me.

**Comment by prattmic** [comment]
We need HUGO_ENV=production?

https://github.com/google/gvisor-website/blob/cb50f7736697225821faec505d0229e250f1251e/themes/docsy/layouts/partials/head.html#L4

**Comment by ianlewis** [comment]
Fixed by #41. Verified that the tag on the website is now
`<META NAME="ROBOTS" CONTENT="INDEX, FOLLOW">`
