### ISSUE TITLE
Docker Quick Start

### ISSUE THREAD

**Issue by xianghaohyman** [google/gvisor-website#48]
docker: Error response from daemon: OCI runtime start failed: /usr/local/bin/runsc did not terminate sucessfully: starting container: setting up network: creating interfaces from net namespace "/proc/7074/ns/net": creating links and routes: urpc method "Network.CreateLinksAndRoutes" failed: EOF
: unknown.

**Comment by fvoznika** [comment]
Please check that you're running Linux 4.14.77 or higher. If not, you can disable Generic
Segmentation Offload (GSO) to run with a kernel that is newer than 3.17. Add the
`--gso=false` flag to your Docker runtime configuration (`/etc/docker/daemon.json`)
and restart the Docker daemon:

 ```json
{
    "runtimes": {
        "runsc": {
            "path": "/usr/local/bin/runsc",
            "runtimeArgs": [
                "--gso=false"
            ]
       }
    }
}
```

We have doc changes in flight to mention this in the quick start guide.

**Comment by ianlewis** [comment]
Can we say that this issue has been addressed by https://github.com/google/gvisor-website/commit/45028bdd82ca3f54d8bb0e99330b1bab6e64cb78 ?
