### ISSUE TITLE
The syscall table eats underscores

### ISSUE THREAD

**Issue by prattmic** [google/gvisor-website#50]
e.g., syscall 310, `process_vm_readv` is listed as `processvmreadv` and links to http://man7.org/linux/man-pages/man2/processvmreadv.2.html, which is a 404.

**Comment by ianlewis** [comment]
Yeah, I noticed this too. I'll address it soon via #30

**Comment by ianlewis** [comment]
Fixed this in https://github.com/google/gvisor-website/commit/0b4eca7b32702a3d88435cc0afb0e169e5c274f0
