### ISSUE TITLE
Links on homepage not displaying properly

### ISSUE THREAD

**Issue by kevinGC** [google/gvisor-website#56]
On both my desktop and mobile, links near the bottom of the page aren't rendering correctly.

![image](https://user-images.githubusercontent.com/1718925/56608592-faa83f80-65bf-11e9-93d1-409f0276246c.png)

**Comment by ianlewis** [comment]
Ack, good catch. I broke it with this change since the content isn't rendered as markdown anymore. Will fix today.
https://github.com/google/gvisor-website/commit/7853b971d43f773002ea92ecc95af7becd9dac55#diff-1413f960ec974b9863bc45d887efa8bd

**Comment by amscanne** [comment]
By the way, I just manually set the serving version to a slightly older version. Should be updated automatically with the next push.
