### ISSUE TITLE
Any reason to not use static_files and static_dir in app.yaml?

### ISSUE THREAD

**Issue by ngrilly** [google/gvisor-website#96]
Is there any reason to serve static files using a handler in main.go, instead of using static_files and static_dir in app.yaml?

https://cloud.google.com/appengine/docs/standard/go112/serving-static-files

**Comment by ianlewis** [comment]
static_dir doesn't support serving index.html files when requesting the root directory. i.e. /docs/ returning /docs/index.html is not supported by static_dir

**Comment by ianlewis** [comment]
Hopefully that explains what we don't use static_dir even though it might be a bit more efficient.

**Comment by ngrilly** [comment]
It can be done in app.yaml with static_files and a regex, but it's true that it's not convenient. Thanks!

**Comment by ianlewis** [comment]
@ngrilly Sure. Feel free to submit a PR if you're inclined to change it.
