### ISSUE TITLE
graphs not rendered on Performance Guide

### ISSUE THREAD

**Issue by mjl-** [google/gvisor-website#99]
https://gvisor.dev/docs/architecture_guide/performance/ has literal text like this:

> {{< graph id=“sysbench-memory” url=“/performance/sysbench-memory.csv” title=“perf.py sysbench.memory –runtime=runc –runtime=runsc” >}}

> {{< graph id=“density” url=“/performance/density.csv” title=“perf.py density –runtime=runc –runtime=runsc” log=“true” y_min=“100000” >}}

Presumably meant to be rendered as an actual graph. Perhaps HTML escaping was accidentally introduced 12 days ago:

https://github.com/google/gvisor-website/commit/46ee8873ffca2468eecf813cb2163f1d31ce390f#diff-55762dff9d787999779edd14062dab33L111

**Comment by amscanne** [comment]
Thanks! I’ve sent a pull request to fix this. I think it was probably an over-eager editor, but I’ll let Ian confirm so we can avoid the problem persisting.

**Comment by ianlewis** [comment]
Yeah, My bad. I fixed it in https://github.com/google/gvisor-website/pull/102
